name: utfprtotem
description: Projeto para a disciplina de Analise e Projeto de Sistemas

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"





# ==========================================================================================> dependencies #

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.3.2
  package_info_plus: ^1.4.2
  sizer: ^2.0.15
  animated_button: ^0.2.0
  
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  provider: ^6.0.3
  
  cupertino_icons: ^1.0.2

# ==========================================================================================> dev_dependencies #

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.6
  build_runner: ^2.1.10

  path: ^1.8.1
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15


  fluttertoast: ^8.0.9

  flutter_lints: ^2.0.0

# ========================================================================================== #

flutter:

  assets:
    - assets/images/
    - assets/config/
    - assets/logo/

  uses-material-design: true
